### ISSUE TITLE
not connect, pls help

### ISSUE THREAD

**Issue by geomen888** [joe-re/vuex-socketio-plugin#1]
Hi, I'm little bit modified your example, I cant obtaine a connection between client and server, pls take look:
store/index.ts 
import Vue from 'vue'
import Vuex, { ActionTree, MutationTree } from 'vuex'
import { socket1 } from './socket1';
import { socket2 } from './socket2';
import { createSocketioPlugin } from 'vuex-socketio-plugin'
import * as io from 'socket.io-client'

Vue.use(Vuex)

 const path1 = '/socket1',
       path2 = '/socket2';     
export const store = new Vuex.Store({
    plugins: [
        createSocketioPlugin(io('http://localhost:8888', { path: path1 })),
        createSocketioPlugin(io('http://localhost:8888', { path: path2 }))
    ],
    state: {},
    mutations: {
        },
    modules: {
        socket1,
        socket2
    },
})
store/socket1.ts; socket2.ts the similar
import { Store, GetterTree, MutationTree, ActionTree, Module } from 'vuex'
import { RootState, SocketState } from '../types'

const state: SocketState = {
    isLogged: false,
    error: '',
    messages: [],
    _client: null
}
const getters: GetterTree<SocketState, RootState> = {
    messages: state => state.messages
}
const mutations: MutationTree<SocketState> = {
SOCKET_CONNECT(state, { client }) {
    state.isLogged = true
    state._client = client
    },
SOCKET_COUNTER(state, { data }){
    state.messages = state.messages.concat([data[0]])
    },
}    
export const socket1: Module<SocketState, RootState> = {
    state,
    getters,
    mutations,
    namespaced: true
}

types.ts
import * as io from 'socket.io-client'

export interface RootState{
    socket1: SocketState
}
export interface SocketState {
    isLogged: boolean
    error: string
    messages: Message[],
   _client: (typeof io.Socket) | null
}
export interface Message {
 message: string
}
server.ts
import * as http from 'http';
import * as socketIo from 'socket.io';
// import { handler } from './handler';
import { SioEvent, SioController, SioNamespace } from '../lib/';
const allowedOrigins = 'http://localhost:8080';
// const app = http.createServer(handler);
const app = http.createServer(function (req, res) {
  res.writeHead(200,  {'Access-Control-Allow-Origin' : allowedOrigins,
   'Access-Control-Allow-Credentials' : 'true',
   'Access-Control-Allow-Headers': ['Content-Type', 'Authorization'],
   'Content-Type': 'text/plain'});
  res.end();
});

const io = socketIo(app);
app.listen(8888);

@SioNamespace({
  name: '/socket1',
  onConnection: [TestIo.onConnection]
})
class TestIo {
  private counter = 1;

  static onConnection(socket) {
    socket.emit('COUNTER', {
      counter: 'Start counting!'
    });
  }

  @SioEvent()
  testMethod(data: any, socket: SocketIO.Socket) {
    console.log(data);
    setTimeout(() => {
      socket.emit('COUNTER', {
        counter: this.counter
      });
      this.counter += 1;
    }, 1000);
  }
}

@SioNamespace({
  name: '/socket2',
  onConnection: [TestIo2.onConnection]
})
class TestIo2 {
  private counter = 1;

  static onConnection(socket) {
    socket.emit('COUNTER2', {
      counter: 'Start counting!'
    });
  }

  @SioEvent()
  testMethod2(data, socket: SocketIO.Socket) {
    console.log(data);
    setTimeout(() => {
      socket.emit('COUNTER2', {
        counter: this.counter
      });
      this.counter += 1;
    }, 1000);
  }
}

const sioCtrl = SioController.getInstance();
sioCtrl.init(io);
and screenshot attached with devtools and Helloworld.vue
![2018-05-10 19-13-37](https://user-images.githubusercontent.com/37697824/39880414-64b4fb44-5486-11e8-81d0-5cf444748438.png)
I dont need to bind server.ts to index.html in case I should develop docker swarm mult-host network with NGINX and I shoud separate server.ts. At present moment it's initial step for better understanding with CORS ... 
So, I'm kindly ask U to provide some advise. Thank U

**Comment by joe-re** [comment]
@geomen888 
`createSocketioPlugin` expects array of socket.io-client instance if you wanna use multi channel.
so you should change usage of `createSocketioPlugin` like below.

```
createSocketioPlugin([
  io('http://localhost:8888', { path: path1 }),
  io('http://localhost:8888', { path: path2 })
])
```

Or are there any net work errors?
Maybe I can provide more help you if you provide completely runnable codes.
It seems like server side codes in your discription are lack a bit to run..

**Comment by joe-re** [comment]
I added multi modules and namespace example.
https://github.com/joe-re/vuex-socketio-plugin/tree/master/example/multi

I hope it helps you.
If you have more questions, please reopen.

**Comment by geomen888** [comment]
Thanks noted. Additional examples are welcome. 

Kind Regards Eugene 



Sent from Mail.Ru app for iOS


Sunday, May 20, 2018, 21:06 +0300 from notifications@github.com  <notifications@github.com>:
